src/utilities/main/default/objects/CS_Trigger_Settings__c/CS_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the list of methods that are available to be enabled / disabled via configuration</description>
    <label>CS Trigger Settings</label>
</CustomObject>

src/utilities/main/default/objects/CS_Trigger_Settings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If method logic should not run on object event, mark as FALSE.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/utilities/main/default/objects/CS_Trigger_Settings__c/fields/Log_Exceptions__c.field-meta.xml
<CustomField>
    <fullName>Log_Exceptions__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If method is unavailable for error handling, mark as FALSE</inlineHelpText>
    <label>Log Exceptions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerHelper.cls
public class TriggerHelper {
    private static Boolean OVERRIDE_TRIGGERHELPER = false;
    private static Boolean OVERRIDE_TRIGGERHELPER_VALUE = true;
    public static Map<String,Boolean> CachedTriggerSettings {get;set;} //Used to turn on/off functionality temporarily
    private static void InitializeCache(){
        if(CachedTriggerSettings == null){
            CachedTriggerSettings = new Map<String,Boolean>();
            Map<String,CS_Trigger_Settings__c> trigSettings = CS_Trigger_Settings__c.getall();
            for(CS_Trigger_Settings__c field : trigSettings.values()){
                CachedTriggerSettings.put(field.Name,field.Enabled__c);
            }
        }
    }
    
    public static Boolean DoExecute(String key){
        if(OVERRIDE_TRIGGERHELPER){return OVERRIDE_TRIGGERHELPER_VALUE;}
        InitializeCache();
        if(CachedTriggerSettings.containsKey(key)){
            return CachedTriggerSettings.get(key);
        }else{
            CS_Trigger_Settings__c newCS = new CS_Trigger_Settings__c(Name = key, Enabled__c = true, Log_Exceptions__c = true);
            insert newCS;
            CachedTriggerSettings.put(key,true);
            return true;
        }
    }
    
    public static void TemporaryOverride(String key, Boolean value){
        InitializeCache();
        CachedTriggerSettings.put(key,value);
    }
    
    public static void OverrideAllSettings(Boolean pTurnOverrideOn, Boolean pValueToOverideWith){
        OVERRIDE_TRIGGERHELPER = pTurnOverrideOn;
        OVERRIDE_TRIGGERHELPER_VALUE = pValueToOverideWith;
    }
}